# Generated by Django 5.1.5 on 2025-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='defaultshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
