[build]
command = "python manage.py migrate"

[build.environment]
DJANGO_SETTINGS_MODULE = "kirr.settings.production"
PYTHON_VERSION = "3.8"

[dev]
command = "python manage.py runserver"
port = 8000

[functions]
directory = "netlify/functions"